export const PROFILE_GET_CURRENT_REQUEST = "PROFILE_GET_CURRENT_REQUEST";
export const PROFILE_GET_CURRENT_SUCCESS = "PROFILE_GET_CURRENT_SUCCESS";
export const PROFILE_GET_CURRENT_FAIL = "PROFILE_GET_CURRENT_FAIL";
export const PROFILE_GET_CURRENT_RESET = "PROFILE_GET_CURRENT_RESET";

export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_FAIL = "PROFILE_CREATE_FAIL";
export const PROFILE_CREATE_RESET = "PROFILE_CREATE_RESET";

export const PROFILE_EDIT_REQUEST = "PROFILE_EDIT_REQUEST";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";
export const PROFILE_EDIT_RESET = "PROFILE_EDIT_RESET";

export const PROFILE_ADD_EXPERIENCE_REQUEST = "PROFILE_ADD_EXPERIENCE_REQUEST";
export const PROFILE_ADD_EXPERIENCE_SUCCESS = "PROFILE_ADD_EXPERIENCE_SUCCESS";
export const PROFILE_ADD_EXPERIENCE_FAIL = "PROFILE_ADD_EXPERIENCE_FAIL";
export const PROFILE_ADD_EXPERIENCE_RESET = "PROFILE_ADD_EXPERIENCE_RESET";

export const PROFILE_ADD_EDUCATION_REQUEST = "PROFILE_ADD_EDUCATION_REQUEST";
export const PROFILE_ADD_EDUCATION_SUCCESS = "PROFILE_ADD_EDUCATION_SUCCESS";
export const PROFILE_ADD_EDUCATION_FAIL = "PROFILE_ADD_EDUCATION_FAIL";
export const PROFILE_ADD_EDUCATION_RESET = "PROFILE_ADD_EXPERIENCE_RESET";

export const PROFILE_DELETE_EXPERIENCE_REQUEST =
  "PROFILE_DELETE_EXPERIENCE_REQUEST";
export const PROFILE_DELETE_EXPERIENCE_SUCCESS =
  "PROFILE_DELETE_EXPERIENCE_SUCCESS";
export const PROFILE_DELETE_EXPERIENCE_FAIL = "PROFILE_DELETE_EXPERIENCE_FAIL";
export const PROFILE_DELETE_EXPERIENCE_RESET =
  "PROFILE_DELETE_EXPERIENCE_RESET";

export const PROFILE_DELETE_EDUCATION_REQUEST =
  "PROFILE_DELETE_EDUCATION_REQUEST";
export const PROFILE_DELETE_EDUCATION_SUCCESS =
  "PROFILE_DELETE_EDUCATION_SUCCESS";
export const PROFILE_DELETE_EDUCATION_FAIL = "PROFILE_DELETE_EDUCATION_FAIL";
export const PROFILE_DELETE_EDUCATION_RESET = "PROFILE_DELETE_EXPERIENCE_RESET";

export const PROFILE_DELETE_ACCOUNT_REQUEST = "PROFILE_DELETE_ACCOUNT_REQUEST";
export const PROFILE_DELETE_ACCOUNT_SUCCESS = "PROFILE_DELETE_ACCOUNT_SUCCESS";
export const PROFILE_DELETE_ACCOUNT_FAIL = "PROFILE_DELETE_ACCOUNT_FAIL";
export const PROFILE_DELETE_ACCOUNT_RESET = "PROFILE_DELETE_EXPERIENCE_RESET";

export const PROFILE_GET_LIST_REQUEST = "PROFILE_GET_LIST_REQUEST";
export const PROFILE_GET_LIST_SUCCESS = "PROFILE_GET_LIST_SUCCESS";
export const PROFILE_GET_LIST_FAIL = "PROFILE_GET_LIST_FAIL";
export const PROFILE_GET_LIST_RESET = "PROFILE_GET_LIST_RESET";

export const PROFILE_GET_BY_ID_REQUEST = "PROFILE_GET_BY_ID_REQUEST";
export const PROFILE_GET_BY_ID_SUCCESS = "PROFILE_GET_BY_ID_SUCCESS";
export const PROFILE_GET_BY_ID_FAIL = "PROFILE_GET_BY_ID_FAIL";
export const PROFILE_GET_BY_ID_RESET = "PROFILE_GET_BY_ID_RESET";

export const PROFILE_GET_GIT_REPO_REQUEST = "PROFILE_GET_GIT_REPO_REQUEST";
export const PROFILE_GET_GIT_REPO_SUCCESS = "PROFILE_GET_GIT_REPO_SUCCESS";
export const PROFILE_GET_GIT_REPO_FAIL = "PROFILE_GET_GIT_REPO_FAIL";
export const PROFILE_GET_GIT_REPO_RESET = "PROFILE_GET_GIT_REPO_RESET";
